### ISSUE TITLE
Error: Width and height must be numbers greater than 0

### ISSUE THREAD

**Issue by yeyeto2788** [Swagielka/simple-homepage#12]
Hey there! 

**Awesome work here**, I'm trying to use this as my personal dash board and I've encountered this issue:

![image](https://user-images.githubusercontent.com/6363686/67213732-d0c0c000-f41e-11e9-909e-f05f3bab4b5a.png)

I'm using Firefox 60.9.0esr (64-bit) and also give the same error on Chrome Version 77.0.3865.120 (Official Build) (64-bit).

Might it be that it might need to take the height and width from other part of the DOM?

Regards.

**P.D:** I'm not an expert on JS so bear with me.

**Comment by IceCreeper28** [comment]
Could not reproduce on Firefox 70.0 nor on Chrome 78.0.3904.70.
I tried opening the file through a server and directly from the file system.
![image](https://user-images.githubusercontent.com/31723351/67954366-20f30b80-fbf1-11e9-9778-6c3e48544a39.png)

**Comment by yeyeto2788** [comment]
@IceCreeper28 thanks for trying it and sorry for my late reply to your comment. I don't see why it should be failing with that I actually got it "working" using the `left` for width if `width` not present and `right` for the `height` but it doesn't sound good for me. I'll try to update the browsers and try it out again.

If the error still persist, I'll try serving the files and see if the error might come from not serving them.

Regards.

**Comment by wiesner-philipp** [comment]
Hey @yeyeto2788!
There must be something wrong with your css files then.
Are you using the latest files?

Greetings.

**Comment by yeyeto2788** [comment]
Hello guys! 

I was using old browsers, my bad for that and for reply this late. I'll close this issue then.

Regards.
