### ISSUE TITLE
PHP -> JS

### ISSUE THREAD

**Issue by fulldecent** [Swagielka/simple-homepage#4]
It is possible to replace the server-side PHP part with client-side JS. This makes the app able to be run in more environments, including GitHub Pages.

**Comment by lil5** [comment]
It would be better to start over. Although I'm considering this because of the abuse of using bootstrap CSS in something so simple

**Comment by the4ndy** [comment]
I tend to agree here, the PHP requirement makes this too heavy for how small/simple it is. If I am going to have a dashboard that requires PHP I would use one that has things like multi user support with login, import/export features, add/remove/edit features in the web gui, etc....something like Heimdall. For something this simple, it needs to be CSS/HTML/JS, able to be saved locally and opened locally without the need for a webserver

**Comment by lil5** [comment]
@the4ndy I've fixed this issue in #6

and here's the fork link https://github.com/lil5/simple-dash

**Comment by wiesner-philipp** [comment]
> @the4ndy I've fixed this issue in #6
> 
> and here's the fork link https://github.com/lil5/simple-dash

Oh boi! Would you mind me integrating this into the master repo?
Github.io pages should work with this flawlessly now. :)

**Comment by lil5** [comment]
@Swagielka I've given you a pull request at #6

Or am I misunderstanding something?

*confused*
