### ISSUE TITLE
Disagree with removal of php version

### ISSUE THREAD

**Issue by lil5** [Swagielka/simple-homepage#7]
For those who hate JavaScript: removal of the PHP version is an anti-feature.

I might even be interested in making a python version just for the fun.

**Links**
- https://github.com/Swagielka/simple-dash/issues/4
- https://github.com/Swagielka/simple-dash/commit/afacf169fe2226dbc33e36da33579b133c281d54

**Comment by wiesner-philipp** [comment]
php is somewhat outdated and doesn't allow to be hosted on github.io.

Closed for now.
